### ISSUE TITLE
Python subprocess not working as expected in OrangePi

### ISSUE THREAD

**Issue by culhacik** [WebMaestroFr/rpi-roam-webapp#6]
I tried your practice in Orange Pi with Ubuntu lxde OS. 

If I run setup.sh, only the access point is created, the Web page is running.
When I use the "ps -ef | grep python" code, __main__py and connection.py do not appear on the screen.

Everything seems fine when I run the "crontab -l" command:

`@reboot sudo rpi-roam-webapp/roam/.env/bin/python rpi-roam-webapp/roam/webapp --ip="10.0.0.1" --port=80 --name="KioskWifi" --ap=wlan0 --adapter=wlan2 &
*/2 * * * * sudo rpi-roam-webapp/roam/.env/bin/python rpi-roam-webapp/roam/webapp/modules/connection.py --ip="10.0.0.1" --port=80 --ap=wlan0 --adapter=wlan2 &`

However, the application is not running. So I used the following code directly on the terminal.

`orangepi@orangepi:~$ sudo rpi-roam-webapp/roam/.env/bin/python rpi-roam-webapp/roam/webapp --ip=\"10.0.0.1\" --port=80 --name=\"KioskWifi\" --ap=\"wlan0\" --adapter=\"wlan2\"`

When I run this code, I get the following error:

`Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/orangepi/rpi-roam-webapp/roam/webapp/__main__.py", line 22, in <module>
    ssid = connection.auto_connect(args.ap, args.adapter)
  File "rpi-roam-webapp/roam/webapp/modules/connection.py", line 83, in auto_connect
    for cell in list_networks(ap):
  File "rpi-roam-webapp/roam/webapp/modules/connection.py", line 42, in list_networks
    return Cell.all(interface)
  File "/home/orangepi/rpi-roam-webapp/roam/.env/local/lib/python2.7/site-packages/wifi/scan.py", line 39, in all
    stderr=subprocess.STDOUT)
  File "/usr/lib/python2.7/subprocess.py", line 567, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory`

Also the "sudo iptables -L" command produces the following result:

`Chain INPUT (policy ACCEPT)
target     prot opt source               destination

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere             state RELATED,ESTABLISHED

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination`

Can you help me for this problem?

**Comment by WebMaestroFr** [comment]
Hi there,
This is working on Raspberry Pi under Raspbian, like specified in the requirements. It hasn't been made or tested for OrangePi ... maybe it's doable. I cannot promess anything, but I will study it.
